import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.imgwrap}>
          {/* <Image className={styles.img} src='/homeimg.avif' alt=" " width={250} height={150} ></Image> */}
          <img className={styles.img} src="/homeimg.avif" alt="hunting coder" width={250} height={150} />
        </div>
        <h1 className={styles.title}>
          <span className="mySpan dummy">
            &lt;Hunting Coder?/&gt;
          </span>
        </h1>
        <div>
          <h2 className={styles.h2}>
            Popular Blogs
          </h2>
          <div>
            <h2 className={styles.h2}>
              How To Learn Next.JS ?
            </h2>
            <p className={styles.p}>
              Next.js is a framework based on javascript for building amazing web app!
            </p>
          </div>
          <div>
            <h2 className={styles.h2}>
              How To Learn Next.JS ?
            </h2>
            <p className={styles.p}>
              Next.js is a framework based on javascript for building amazing web app!
            </p>
          </div>
          <div>
            <h2 className={styles.h2}>
              How To Learn Next.JS ?
            </h2>
            <p className={styles.p}>
              Next.js is a framework based on javascript for building amazing web app!
            </p>
          </div>
        </div>
      </main >
    </div >
  )
}
